force-app/main/default/objects/TU_CR_Settings__c/TU_CR_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TU CR Settings</label>
</CustomObject>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>TU_Certificate_Name__c</fullName>
    <label>TU Certificate Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Credit_API_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>TU_Credit_API_Endpoint__c</fullName>
    <label>TU Credit API Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Credit_API_Port__c.field-meta.xml
<CustomField>
    <fullName>TU_Credit_API_Port__c</fullName>
    <label>TU Credit API Port</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>TU_Industry_Code__c</fullName>
    <label>TU Industry Code</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Inquiry_Subscriber_Prefix_Code__c.field-meta.xml
<CustomField>
    <fullName>TU_Inquiry_Subscriber_Prefix_Code__c</fullName>
    <label>TU Inquiry Subscriber Prefix Code</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Member_Code__c.field-meta.xml
<CustomField>
    <fullName>TU_Member_Code__c</fullName>
    <label>TU Member Code</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Password__c.field-meta.xml
<CustomField>
    <fullName>TU_Password__c</fullName>
    <label>TU Password</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_System_Password__c.field-meta.xml
<CustomField>
    <fullName>TU_System_Password__c</fullName>
    <label>TU System Password</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_SystemID__c.field-meta.xml
<CustomField>
    <fullName>TU_SystemID__c</fullName>
    <label>TU System ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Vendor_Id__c.field-meta.xml
<CustomField>
    <fullName>TU_Vendor_Id__c</fullName>
    <label>TU Vendor Id</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateTUCRSettings.cls
public class UpdateTUCRSettings {
    
    @InvocableMethod(label='Update TUCR setting' description='To update TransUnion credit report custom setting' category='TU4SF')
    public static void UpdateTransUnionSettings(List<String> inputList) {
        
        // Check if PermissionSet object is accessible
		if (Schema.sObjectType.PermissionSet.isAccessible()) {
			String permissionSetName = 'TransUnion_for_Salesforce';
            Boolean hasPermissionSetAssigned=[SELECT Id 
                                              FROM PermissionSetAssignment 
                                              WHERE PermissionSet.Name = :permissionSetName 
                                              AND AssigneeId = :UserInfo.getUserId()
                                             ].size()!=0;
            
			if(hasPermissionSetAssigned) {
                TU_CR_Settings__c transUnionSettings = TU_CR_Settings__c.getOrgDefaults();
                List<TU_CR_Settings__c> settingsToUpdate = new List<TU_CR_Settings__c>();
                
                for (String input : inputList) {
                    Map<String, String> keyValuePairs = parseInput(input);
                    transUnionSettings.TU_Industry_Code__c = keyValuePairs.get('IndustryCode');
                    transUnionSettings.TU_Inquiry_Subscriber_Prefix_Code__c = keyValuePairs.get('Inquiry');
                    transUnionSettings.TU_Member_Code__c = keyValuePairs.get('Member');
                    transUnionSettings.TU_Password__c = keyValuePairs.get('Password');
                    transUnionSettings.TU_Vendor_Id__c = keyValuePairs.get('Vendor');
                    transUnionSettings.TU_System_Password__c = keyValuePairs.get('SystemPassword');
                    transUnionSettings.TU_Certificate_Name__c = keyValuePairs.get('Certificate'); 
                    transUnionSettings.TU_SystemID__c = keyValuePairs.get('SystemID');
                    transUnionSettings.TU_Credit_API_Port__c = keyValuePairs.get('Port');
                    transUnionSettings.TU_Credit_API_Endpoint__c =keyValuePairs.get('EndPoint');
                    settingsToUpdate.add(transUnionSettings);
                }
                update settingsToUpdate;
            } 
    	}
    }
        
    //Method to parse the input received
    private static Map<String, String> parseInput(String input) {
        Map<String, String> keyValuePairs = new Map<String, String>();
        List<String> pairs = input.split(',');
        
        for (String pair : pairs) {
            List<String> keyValue = pair.split('=');
            
            if (keyValue.size() == 2) {
                keyValuePairs.put(keyValue[0].trim(), keyValue[1].trim());
            }            
        }
        return keyValuePairs;
    }
}