force-app/main/default/objects/TU_CR_Settings__c/TU_CR_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TU CR Settings</label>
</CustomObject>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>TU_Certificate_Name__c</fullName>
    <label>TU Certificate Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Credit_API_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>TU_Credit_API_Endpoint__c</fullName>
    <label>TU Credit API Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Credit_API_Port__c.field-meta.xml
<CustomField>
    <fullName>TU_Credit_API_Port__c</fullName>
    <label>TU Credit API Port</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>TU_Industry_Code__c</fullName>
    <label>TU Industry Code</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Inquiry_Subscriber_Prefix_Code__c.field-meta.xml
<CustomField>
    <fullName>TU_Inquiry_Subscriber_Prefix_Code__c</fullName>
    <label>TU Inquiry Subscriber Prefix Code</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Member_Code__c.field-meta.xml
<CustomField>
    <fullName>TU_Member_Code__c</fullName>
    <label>TU Member Code</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Password__c.field-meta.xml
<CustomField>
    <fullName>TU_Password__c</fullName>
    <label>TU Password</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_System_Password__c.field-meta.xml
<CustomField>
    <fullName>TU_System_Password__c</fullName>
    <label>TU System Password</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_SystemID__c.field-meta.xml
<CustomField>
    <fullName>TU_SystemID__c</fullName>
    <label>TU System ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Vendor_Id__c.field-meta.xml
<CustomField>
    <fullName>TU_Vendor_Id__c</fullName>
    <label>TU Vendor Id</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_UpdateTUCRSettings.cls
@isTest
public class Test_UpdateTUCRSettings {
    @isTest
    static void UpdateTUCRSettings() {
        // Create test data
        TU_CR_Settings__c transUnionSettings = new TU_CR_Settings__c();  
        transUnionSettings.TU_Industry_Code__c = 'T';
        transUnionSettings.TU_Certificate_Name__c = 'Tucr';    
        transUnionSettings.TU_Inquiry_Subscriber_Prefix_Code__c = '0522';
        transUnionSettings.TU_Member_Code__c = '1234567';
        transUnionSettings.TU_Password__c = 'L1Y2';
        transUnionSettings.TU_Vendor_Id__c = '1234';
        transUnionSettings.TU_SystemID__c = 'Dynamisch';
        transUnionSettings.TU_System_Password__c = 'Dynamisch123';
        transUnionSettings.TU_Credit_API_Endpoint__c = 'https://nacam-test.transunion.com';
        transUnionSettings.TU_Credit_API_Port__c = '443';
        insert transUnionSettings;
        transUnionSettings.TU_Industry_Code__c = 'I';
        update transUnionSettings;
        
        // Create inputList
        List<String> inputList = new List<String>{'IndustryCode=T, Inquiry=0522, Member=1234567, Password=L1Y2, Vendor=1234,SystemID=Dynamisch,SystemPassword=Dynamisch123,Certificate=Tucr,Port=443,EndPoint=https://nacam-test.transunion.com'};
        
        Test.startTest();
        UpdateTUCRSettings.UpdateTransUnionSettings(inputList);
        Test.stopTest();
  		
        System.assertEquals(1, inputList.size(), 'Custom setting values updated');
        
    }
}