force-app/main/default/objects/TU_CR_Settings__c/TU_CR_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TU CR Settings</label>
</CustomObject>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>TU_Certificate_Name__c</fullName>
    <label>TU Certificate Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Credit_API_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>TU_Credit_API_Endpoint__c</fullName>
    <label>TU Credit API Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Credit_API_Port__c.field-meta.xml
<CustomField>
    <fullName>TU_Credit_API_Port__c</fullName>
    <label>TU Credit API Port</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>TU_Industry_Code__c</fullName>
    <label>TU Industry Code</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Inquiry_Subscriber_Prefix_Code__c.field-meta.xml
<CustomField>
    <fullName>TU_Inquiry_Subscriber_Prefix_Code__c</fullName>
    <label>TU Inquiry Subscriber Prefix Code</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Member_Code__c.field-meta.xml
<CustomField>
    <fullName>TU_Member_Code__c</fullName>
    <label>TU Member Code</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Password__c.field-meta.xml
<CustomField>
    <fullName>TU_Password__c</fullName>
    <label>TU Password</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_System_Password__c.field-meta.xml
<CustomField>
    <fullName>TU_System_Password__c</fullName>
    <label>TU System Password</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_SystemID__c.field-meta.xml
<CustomField>
    <fullName>TU_SystemID__c</fullName>
    <label>TU System ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TU_CR_Settings__c/fields/TU_Vendor_Id__c.field-meta.xml
<CustomField>
    <fullName>TU_Vendor_Id__c</fullName>
    <label>TU Vendor Id</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_callTransUnionCRAction.cls
@isTest
global class Test_callTransUnionCRAction {
    // Method to create and return mock settings with the required fields set
    private static TU_CR_Settings__c createMockSettings() {
        TU_CR_Settings__c transUnionSettings = new TU_CR_Settings__c();
        transUnionSettings.TU_Industry_Code__c = 'T';
        transUnionSettings.TU_Certificate_Name__c='tucrcertsf2';	
        transUnionSettings.TU_Inquiry_Subscriber_Prefix_Code__c = '0522';
        transUnionSettings.TU_Member_Code__c = '1234567';
        transUnionSettings.TU_Password__c = 'L1Y2';
        transUnionSettings.TU_Vendor_Id__c = '1234';
        transUnionSettings.TU_SystemID__c='Dynamisch';
        transUnionSettings.TU_System_Password__c='Dynamisch123';
        transUnionSettings.TU_Credit_API_Endpoint__c='https://nacam-test.transunion.com';
        transUnionSettings.TU_Credit_API_Port__c='443';
        insert transUnionSettings;
        return transUnionSettings;
    }
    
    @isTest
    private static void testSoapCalloutSuccess() {
        TU_CR_Settings__c transUnionSettings = createMockSettings();
        // Test data
        List<String> creditOutput = new List<String>{'SSNNumber%%%123456789',
            									     'FirstName%%%John',
                                                     'LastName%%%Doe',
                                                     'Apartmentnumber%%%Apt 123',
                                                     'Street%%%Main St',
                                                     'City%%%Springfield',
                                                     'State%%%IL',
                                                     'PostalCode%%%12345',
                                                     'RecordId%%%003an000001LvIrAAK'};
		Test.setMock(HttpCalloutMock.class, new mockHttpResponseGenerator());
        
        Test.startTest();
        List<String> result = callTransUnionCRAction.callTransUnionCR(creditOutput);
        Test.stopTest();
        
        System.assertEquals(1, result.size(), 'Expected only one result');
    }
    
    @isTest
    private static void testSoapCalloutError() {
        TU_CR_Settings__c transUnionSettings = createMockSettings();
        List<String> creditOutput = new List<String>{'SSNNumber%%%123456789',
                                                     'FirstName%%%John',
                                                     'LastName%%%Doe',
                                                     'Apartmentnumber%%%Apt 123',
                                                     'Street%%%Main St',
                                                     'City%%%Springfield',
                                                     'State%%%IL',
                                                     'PostalCode%%%12345',
                                                     'RecordId%%%003an000001LvIrAwg'};
		Test.setMock(HttpCalloutMock.class, new mockHttpResponseGeneratorError());
        
        Test.startTest();
        List<String> result = callTransUnionCRAction.callTransUnionCR(creditOutput);
        Test.stopTest();
        
        System.assert(result != null, 'An error should be returned');
    } 
    
    // Mock HTTP response generator for success
    private class mockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'text/xml');
            res.setBody('<response><fileHitIndicator>regularHit</fileHitIndicator><fileHitIndicator>error</fileHitIndicator><fileHitIndicator>Other</fileHitIndicator><fileHitIndicator>regularnohit</fileHitIndicator><address><street>hinjewadi</street></address><address><street>hinjewadi1</street></address><address><street>hinjewadi2</street></address><results>+750</results><transactionTimeStamp>2024-04-05T12:00:00Z</transactionTimeStamp><embeddedData>fake embedded data</embeddedData><error><description>Error message</description></error></response>');
            res.setStatusCode(200);
            return res;
        }
    }
    
    // Mock HTTP response generator for error
    private class mockHttpResponseGeneratorError implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'text/xml');
            res.setBody('<error><errormessage>Your Subscriber Code is not linked with the System ID.</errormessage><description>Error occurred</description></error>');
            res.setStatusCode(500);
            res.setStatus('500 Internal Server Error');
            return res;
        }
    }
}